version: '3'
services:
  ros_container:
    image: ros_flightsim:0.6
    ports:
      - "8080:3000"
    environment:
      DISPLAY: ${DISPLAY}
    volumes:
      - /home/penguin/fm/flightmare:/home/user/fm/flightmare
      - /etc/hosts:/etc/hosts
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    tty: true
    container_name: ros_fm
